service: simple-app

frameworkVersion: ">=1.1.0 <2.0.0"

provider:
  name: aws
  stage: develop
  region: eu-west-1
  runtime: nodejs4.3

functions:
  events:
    handler: src/app/hello-world/handler.endpoint
    events:
      - http:
          path: hello
          method: get